apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: gcs-repository
  namespace: demo
spec:
  backend:
    gcs:
      bucket: kubedb-testing
      prefix: /elasticsearch
    storageSecretName: gcs-secret