apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cluster-gateway-addon-manager
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: cluster-gateway-addon-manager
  targetNamespace: open-cluster-management
  storageNamespace: open-cluster-management
  chart:
    spec:
      chart: cluster-gateway-addon-manager
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  dependsOn:
    - name: cluster-manager-hub
    - name: managed-serviceaccount
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    manualSecretManagement: false
    konnectivityEgress: true
