apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: managed-serviceaccount
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: managed-serviceaccount
  targetNamespace: open-cluster-management
  storageNamespace: open-cluster-management
  chart:
    spec:
      chart: managed-serviceaccount
      version: "0.4.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  dependsOn:
    - name: cluster-manager-hub
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
