apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-operator
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: external-dns-operator
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: external-dns-operator
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: external-dns-operator
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
    upgrade:
      crds: CreateReplace
      remediation:
        retries: -1
