apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubedb-opscenter
  namespace: kubeops
  labels:
    app.kubernetes.io/component: kubedb-opscenter
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubedb-opscenter
  targetNamespace: kubedb
  storageNamespace: kubedb
  chart:
    spec:
      chart: kubedb-opscenter
      version: "v2023.10.26-rc.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
