apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux2
  namespace: kubeops
  labels:
    app.kubernetes.io/component: flux2
spec:
  interval: 5m
  timeout: 30m
  releaseName: flux2
  targetNamespace: flux-system
  storageNamespace: flux-system
  chart:
    spec:
      chart: flux2
      version: "2.12.1"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    helmController:
      create: true
      labels:
        ace.appscode.com/managed: "true"
    sourceController:
      create: true
      labels:
        ace.appscode.com/managed: "true"
    imageAutomationController:
      create: false
    imageReflectionController:
      create: false
    kustomizeController:
      create: false
    notificationController:
      create: false
