apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-ui-server
  namespace: kubeops
  labels:
    app.kubernetes.io/component: kube-ui-server
spec:
  interval: 5m
  timeout: 30m
  releaseName: kube-ui-server
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: kube-ui-server
      version: "v2023.10.1"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
