apiVersion: v1
kind: Secret
metadata:
  name: vault-unsealer-gcp-creds
  namespace: demo
stringData:
  sa.json: |-
    {
      "key": "value",
    }
type: Opaque
---
apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  backend:
    raft:
      path: /vault/data
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
  replicas: 1
  unsealer:
    mode:
      googleKmsGcs:
        bucket: <bucket-name>
        credentialSecret: vault-unsealer-gcp-creds
        kmsCryptoKey: <kms-key>
        kmsKeyRing: <kms-ring>
        kmsLocation: <kms-location>
        kmsProject: <project-name>
    secretShares: 5
    secretThreshold: 3
  version: 1.8.2
