apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: kubeops
  labels:
    app.kubernetes.io/component: crossplane
spec:
  interval: 5m
  timeout: 30m
  releaseName: crossplane
  targetNamespace: crossplane-system
  storageNamespace: crossplane-system
  chart:
    spec:
      chart: crossplane
      version: "1.13.2"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
