apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: kubeops
  labels:
    ace.appscode.com/feature: keda
spec:
  interval: 5m
  timeout: 30m
  releaseName: keda
  targetNamespace: keda
  storageNamespace: keda
  chart:
    spec:
      chart: keda
      version: ""
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: keda
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
