apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda-add-ons-http
  namespace: kubeops
  labels:
    app.kubernetes.io/component: keda-add-ons-http
spec:
  interval: 5m
  timeout: 30m
  releaseName: keda-add-ons-http
  targetNamespace: keda
  storageNamespace: keda
  chart:
    spec:
      chart: keda-add-ons-http
      version: "0.6.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
