apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kubeops
spec:
  interval: 30m
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "v1.11.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
