apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
  namespace: demo
stringData:
  user.conf: |
    max_connections=110
    shared_buffers=258MB
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: postgres-ca-issuer
  namespace: demo
spec:
  ca:
    secretName: postgres-ca
---
apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: postgres
  namespace: demo
spec:
  clientAuthMode: scram
  configSecret:
    name: postgres-config
  init:
    waitForInitialRestore: true
  leaderElection:
    electionTick: 10
    heartbeatTick: 1
    maximumLagBeforeFailover: 33554432
    period: 100ms
  replicas: 3
  sslMode: verify-full
  standbyMode: Hot
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: postgres-ca-issuer
  version: "13.2"
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgreses.kubedb.com
  name: postgres-init-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/postgres
    storageSecretName: gcs-secret
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgreses.kubedb.com
  name: postgres-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/postgres
    storageSecretName: gcs-secret
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgreses.kubedb.com
  name: postgres
  namespace: demo
spec:
  repository:
    name: postgres-init-repo
  retentionPolicy:
    keepLast: 5
    name: keep-last-5
    prune: true
  schedule: '*/2 * * * *'
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: postgres
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgreses.kubedb.com
  name: postgres-init
  namespace: demo
spec:
  repository:
    name: postgres-init-repo
  rules:
  - snapshots:
    - latest
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: postgres
