apiVersion: v1
kind: Secret
metadata:
  name: proxysql-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: proxysql-config
  namespace: demo
stringData:
  md-config.cnf: |
    [mysqld]
    max_connections = 200
    read_buffer_size = 1048576
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: proxysql-ca
  namespace: demo
spec:
  ca:
    secretName: proxysql-ca
---
apiVersion: kubedb.com/v1alpha2
kind: ProxySQL
metadata:
  name: proxysql
  namespace: demo
spec:
  authSecret:
    name: proxysql-auth
  configSecret:
    name: proxysql-config
  monitor:
    agent: prometheus.io
    prometheus:
      serviceMonitor:
        interval: 30s
        labels:
          release: prometheus-stack
  podTemplate:
    spec:
      args:
      - --character-set-server=utf8mb4
      env:
      - name: MYSQL_DATABASE
        value: mdDB
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
  replicas: 1
  terminationPolicy: WipeOut
  tls:
    certificates:
    - alias: server
      dnsNames:
      - localhost
      ipAddresses:
      - 127.0.0.1
      subject:
        organizations:
        - kubedb:server
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: proxysql-ca
  version: 10.5.8
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: proxysql
    app.kubernetes.io/name: proxysqls.kubedb.com
    release: prometheus-stack
  name: proxysql
  namespace: demo
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: proxysql
      app.kubernetes.io/name: proxysqls.kubedb.com
