apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: topolvm
  namespace: kubeops
  labels:
    app.kubernetes.io/component: topolvm
spec:
  interval: 5m
  timeout: 30m
  releaseName: topolvm
  targetNamespace: topolvm-system
  storageNamespace: topolvm-system
  chart:
    spec:
      chart: topolvm
      version: 13.0.0
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
