apiVersion: v1
kind: Secret
metadata:
  name: vault-backend-postgresql-creds
  namespace: demo
stringData:
  connection_url: <connection_url>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-unsealer-aws-creds
  namespace: demo
stringData:
  access_key: <access_key>
  secret_key: <secret_key>
type: Opaque
---
apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  backend:
    postgresql:
      connectionURLSecret: vault-backend-postgresql-creds
  replicas: 1
  unsealer:
    mode:
      awsKmsSsm:
        credentialSecret: vault-unsealer-aws-creds
        kmsKeyID: <kms-key-id>
        region: <region>
    secretShares: 5
    secretThreshold: 3
  version: 1.8.2
