apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: kubeops
  labels:
    app.kubernetes.io/component: reloader
spec:
  interval: 5m
  timeout: 30m
  releaseName: reloader
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: reloader
      version: "1.0.50"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
